import type { ThemePreset } from "./themes";

// Palette references and adaptation notes: docs/themes.md.
type Colors = [string, string, string, string, string, string];
function preset(
  id: string,
  name: string,
  description: string,
  category: "dark" | "light",
  bg: string,
  panel: string,
  fg: string,
  muted: string,
  border: string,
  colors: Colors,
): ThemePreset {
  const [red, green, yellow, blue, magenta, cyan] = colors;
  return {
    id,
    name,
    description,
    category,
    ui: {
      bg,
      panel,
      panelAlt: panel,
      fg,
      muted,
      border,
      accent: blue,
      danger: red,
    },
    term: {
      background: bg,
      foreground: fg,
      cursor: fg,
      cursorAccent: bg,
      selectionBackground: border,
      black: category === "dark" ? panel : "#343b45",
      red,
      green,
      yellow,
      blue,
      magenta,
      cyan,
      white: category === "dark" ? fg : "#d8dee9",
      brightBlack: muted,
      brightRed: red,
      brightGreen: green,
      brightYellow: yellow,
      brightBlue: blue,
      brightMagenta: magenta,
      brightCyan: cyan,
      brightWhite: category === "dark" ? "#f8f8f2" : "#f5f5f5",
    },
  };
}
const oneDark = preset(
  "one-dark-pro",
  "One Dark Pro",
  "经典蓝灰底，清晰的蓝绿与暖橙",
  "dark",
  "#282c34",
  "#21252b",
  "#abb2bf",
  "#9da5b4",
  "#3e4452",
  ["#e05561", "#8cc265", "#d18f52", "#4aa5f0", "#c162de", "#42b3c2"],
);
Object.assign(oneDark.term, {
  black: "#3f4451",
  white: "#d7dae0",
  brightBlack: "#4f5666",
  brightRed: "#ff616e",
  brightGreen: "#a5e075",
  brightYellow: "#f0a45d",
  brightBlue: "#4dc4ff",
  brightMagenta: "#de73ff",
  brightCyan: "#4cd1e0",
  brightWhite: "#e6e6e6",
});
const monokai = preset(
  "monokai-pro",
  "Monokai Pro (CE)",
  "暖灰底色，经典粉红、杏黄与青绿",
  "dark",
  "#2d2a2e",
  "#221f22",
  "#fcfcfa",
  "#b1afb3",
  "#5b595c",
  ["#ff6188", "#a9dc76", "#ffd866", "#78dce8", "#ab9df2", "#78dce8"],
);
const dracula = preset(
  "dracula",
  "Dracula",
  "紫灰夜色，粉紫与薄荷绿",
  "dark",
  "#282a36",
  "#21222c",
  "#f8f8f2",
  "#a6accd",
  "#44475a",
  ["#ff5555", "#50fa7b", "#f1fa8c", "#bd93f9", "#ff79c6", "#8be9fd"],
);
const solarColors: Colors = [
  "#dc322f",
  "#859900",
  "#b58900",
  "#268bd2",
  "#d33682",
  "#2aa198",
];
const solarDark = preset(
  "solarized-dark",
  "Solarized Dark",
  "深青底色，温和的复古对比",
  "dark",
  "#002b36",
  "#073642",
  "#93a1a1",
  "#839496",
  "#24505a",
  solarColors,
);
const solarLight = preset(
  "solarized-light",
  "Solarized Light",
  "暖纸色工具区与终端",
  "light",
  "#fdf6e3",
  "#eee8d5",
  "#586e75",
  "#657b83",
  "#d6cfba",
  solarColors,
);
const classic = preset(
  "monokai-classic",
  "Monokai Classic",
  "橄榄黑背景，鲜明的经典配色",
  "dark",
  "#272822",
  "#20211c",
  "#f8f8f2",
  "#b0b09e",
  "#49483e",
  ["#f92672", "#a6e22e", "#e6db74", "#66d9ef", "#ae81ff", "#a1efe4"],
);
const graphiteLight = preset(
  "paper-light",
  "Paper · 素纸",
  "中性白与墨灰，简洁清楚",
  "light",
  "#ffffff",
  "#f4f5f7",
  "#24292f",
  "#57606a",
  "#d0d7de",
  ["#b42332", "#1a7431", "#846000", "#0969da", "#8250df", "#087e8b"],
);
const roseLight = preset(
  "rose-paper",
  "Rose Paper · 玫瑰纸",
  "暖白纸面，柔和玫瑰紫点缀",
  "light",
  "#fff8f5",
  "#f6ede9",
  "#493d49",
  "#766574",
  "#e3d4d9",
  ["#b63d55", "#397452", "#8b651c", "#8a527c", "#9654a3", "#247a81"],
);
const ocean = preset(
  "ocean-deep",
  "Ocean · 深海",
  "深蓝背景，清透青色强调",
  "dark",
  "#101e2b",
  "#152635",
  "#d5e4ee",
  "#92adbd",
  "#304758",
  ["#ef7b87", "#91d4a2", "#edcb82", "#7bbbe7", "#bdabeb", "#75d4d0"],
);
const forest = preset(
  "forest-night",
  "Forest · 森林夜色",
  "偏绿炭灰，柔和自然色",
  "dark",
  "#202925",
  "#18211d",
  "#dce5d8",
  "#a0b09f",
  "#405046",
  ["#e58c89", "#a6c98c", "#d8c58b", "#91bfbd", "#c7a1bd", "#85c9b2"],
);
const ink = preset(
  "ink-black",
  "Ink · 墨黑",
  "接近纯黑，冷白文字与蓝色强调",
  "dark",
  "#0c0e12",
  "#14171d",
  "#e1e5ec",
  "#969fae",
  "#343b46",
  ["#f08088", "#8ed4a1", "#e7c779", "#83b3f5", "#bda0eb", "#80d0db"],
);

function mixed(
  id: string,
  name: string,
  description: string,
  ui: ThemePreset,
  terminal: ThemePreset,
  accent: string,
): ThemePreset {
  return {
    id,
    name,
    description,
    category: "mixed",
    ui: { ...ui.ui, accent },
    term: { ...terminal.term },
  };
}
export const EXTRA_THEMES: ThemePreset[] = [
  oneDark,
  monokai,
  classic,
  dracula,
  solarDark,
  solarLight,
  graphiteLight,
  roseLight,
  ocean,
  forest,
  ink,
  mixed(
    "hybrid-emerald",
    "Emerald · 翡翠工作台",
    "浅色工具面板＋炭黑终端，清爽绿点缀",
    graphiteLight,
    classic,
    "#16834a",
  ),
  mixed(
    "hybrid-blue",
    "Studio · 蓝白工作台",
    "浅灰工具面板＋One Dark 终端",
    graphiteLight,
    oneDark,
    "#2563eb",
  ),
  mixed(
    "hybrid-paper",
    "Paper Night · 暖纸夜色",
    "暖纸工具面板＋深青终端",
    solarLight,
    solarDark,
    "#267d84",
  ),
  mixed(
    "hybrid-rose",
    "Rose Night · 玫瑰夜色",
    "暖白工具面板＋Dracula 终端",
    roseLight,
    dracula,
    "#8a527c",
  ),
];
